### ISSUE TITLE
Error Message: a.trim is not a function

### ISSUE THREAD

**Issue by markharrisonms** [microsoft/vscode-apimanagement#192] opened 2021-03-27 15:10 UTC
Does this occur consistently? Yes
1.  import API
2. select :  https://coloursapi.azurewebsites.net/swagger/v1/swagger.json

Action: azureApiManagement.importOpenApiByLink
Error type: TypeError
Error Message: a.trim is not a function

Version: 1.0.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:611:6457
fulfilled extension.bundle.js:611:4706
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by RupengLiu** [comment] 2021-03-29 19:09
open API 3.0 swagger

**Comment by miaojiang** [comment] 2021-03-29 20:08
Duplicate of #9, will be included in the next version.

**Closed by miaojiang** 2021-03-29 20:08 UTC
