### ISSUE TITLE
 API version query parameter is not specified or was specified incorrectly

### ISSUE THREAD

**Issue by rshetty-ws** [microsoft/vscode-apimanagement#346] opened 2024-02-23 19:23 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureApiManagement.showServicePolicy
Error type: Error
Error Message: API version query parameter is not specified or was specified incorrectly.  Supported versions: 2021-08-01,2021-12-01-preview,2022-04-01-preview,2022-08-01,2022-09-01-preview,2023-03-01-preview,2023-05-01-preview,2023-09-01-preview  Example query param format: api-version=SupportedVersion

Version: 1.0.8
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.86.2
Language: en

<details>
<summary>Call Stack</summary>

```
ServicePolicyEditor.<anonymous> extension.bundle.js:16:392980
rejected extension.bundle.js:16:392126
```

</details>

**Comment by lars-pehrsson** [comment] 2024-03-22 04:47
For a quick fix you can edit this file,
 ~/.vscode/extensions/ms-azuretools.vscode-apimanagement-1.0.8/dist/extension.bundle.js
replace the two "2019-12-01" with "2021-08-01" and it should work.
Hopefully one day MS will change the correct line, https://github.com/microsoft/vscode-apimanagement/blob/6e590a25b7cb5961f2c2bfb4306f5b1eab915d0d/src/constants.ts#L33

**Comment by larspehrsson** [comment] 2024-03-26 00:28
For a quick fix you can edit this file,
 ~/.vscode/extensions/ms-azuretools.vscode-apimanagement-1.0.8/dist/extension.bundle.js
replace the two "2019-12-01" with "2021-08-01" and it should work.
Hopefully one day MS will change the correct line, https://github.com/microsoft/vscode-apimanagement/blob/6e590a25b7cb5961f2c2bfb4306f5b1eab915d0d/src/constants.ts#L33

**Comment by judebevan** [comment] 2024-07-19 05:54
I changed the enforce minimum API version into Yes, previously I was able to connect to my API manager via VS Code but after this change I'm unable to connect, did the above-mentioned changes also but did not work what to do for this

![image](https://github.com/user-attachments/assets/bd51e30e-63a8-4dc8-b169-786a07a88dca)

**Comment by tomkerkhove** [comment] 2024-07-19 11:21
Duplicate of https://github.com/microsoft/vscode-apimanagement/issues/317

**Closed by tomkerkhove** 2024-07-19 11:21 UTC
