### ISSUE TITLE
VSCode : Error Message: API version query parameter is not specified or was specified incorrectly

### ISSUE THREAD

**Issue by adam-tnt** [microsoft/vscode-apimanagement#360] opened 2024-07-17 08:20 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureApiManagement.showServicePolicy
Error type: Error
Error Message: API version query parameter is not specified or was specified incorrectly.  Supported versions: 2021-08-01,2021-12-01-preview,2022-04-01-preview,2022-08-01,2022-09-01-preview,2023-03-01-preview,2023-05-01-preview,2023-09-01-preview  Example query param format: api-version=SupportedVersion

Version: 1.0.8
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.89.1
Language: en

<details>
<summary>Call Stack</summary>

```
ServicePolicyEditor.<anonymous> extension.bundle.js:16:392980
rejected extension.bundle.js:16:392126
```

</details>

**Comment by tomkerkhove** [comment] 2024-07-19 11:21
Duplicate of https://github.com/microsoft/vscode-apimanagement/issues/317

**Closed by tomkerkhove** 2024-07-19 11:21 UTC
